name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git safe directory
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v4
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: bastardkb/bastardkb-qmk
      qmk_ref: main

  publish:
    name: 'QMK Userspace Publish'
    uses: bastardkb/qmk_userspace/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: build
